### ISSUE TITLE
I am unable to add bitcodin-dotnet package in my asp.net core 1.0.0 project

### ISSUE THREAD

**Issue by flabbert** [bitmovin/bitcodin-dotnet#1]
```
Package bitcodin-dotnet 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package bitcodin-dotnet 1.0.0 supports: net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

project was upgraded from RC2 to 1.0.0 and compiles fine before adding this package.

**Comment by SInCE** [comment]
Hi flabbert,
thank you very much for pointing that out, will investigate that as soon as possible.

**Comment by SInCE** [comment]
Hi again,
unfortunately, .NET Core isn't supported at the moment, as it only contains a subset of features of the .NET Framework. Would you mind to briefly describe why you would need the compatibility with .NET Core?

**Comment by flabbert** [comment]
We are using it to host our control system for streaming clients. This system is hosted on a linux based host. If we use the full .net system we are not able to host it on anything but a windows server. This is unfortunately not an option.
