### ISSUE TITLE
BitcodinApi.cs ListTransfers issue

### ISSUE THREAD

**Issue by peia** [bitmovin/bitcodin-dotnet#3]
```
public Transfer.Transfer[] ListTransfers(TransferConfig id)
{
    return Get<Transfer.Transfer[]>($"job/{id}/transfers");
}
```

the type of the id parameter is strange and it gives an error.

**Comment by msmole** [comment]
Thank you for pointing that out. I just changed it to the following

```
public Transfer.Transfer[] ListTransfers(int jobId)
{
    return Get<Transfer.Transfer[]>($"job/{jobId}/transfers");
}
```

**Comment by msmole** [comment]
Here is the commit for reference:
https://github.com/bitmovin/bitcodin-dotnet/commit/cf6e4aec75425eb46589d5ba7d9fe4f6cf501ce6
